### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by FarhanGamal** [fakhirula/percobaan#1]
ada bug saat melakukan login

**Comment by FarhanGamal** [comment]
![Screenshot (111)](https://github.com/user-attachments/assets/0428345c-5b2a-4490-a7a6-2554144b2692)

**Comment by fakhirula** [comment]
bugnya seperti apa? ada pesan atau kode error tidak?

**Comment by FarhanGamal** [comment]
ada bug 404 saat sudah masuk ke login

**Comment by fakhirula** [comment]
bugnya sudah diperbaiki oleh tim dev, silakan dicoba kembali

**Comment by Azhar-Fikri99** [comment]
tess

**Comment by FarhanGamal** [comment]
test
